src/Entity/Event.php
<?php                                      
                                                     
namespace App\Entity;

use App\Contracts\TimestampableRdg\TimestampableRdgInterface;
use App\Contracts\TimestampableRdg\TimestampableRdgTrait;
use App\Repository\EventRepository;
use App\Tool\DateTool;
use App\Validator as RdgAssert;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Contract\Entity\TranslatableInterface;
use Knp\DoctrineBehaviors\Model\Translatable\TranslatableTrait;

/**
 * @ORM\Entity(repositoryClass=EventRepository::class)
 * @ORM\Table(name="event")
 * @ORM\HasLifecycleCallbacks()
 *
 * @RdgAssert\Constraint\EventConstraint()
 */
class Event implements TranslatableInterface, TimestampableRdgInterface
{
    use TranslatableTrait;
    use TimestampableRdgTrait;

    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var \DateTime
     *
     * @ORM\Column(type="datetime")
     */
    private $begin;

    /**
     * @var \DateTime|null
     *
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $end;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255)
     */
    private $link;

    /**
     * Publication is manually control and can be schedule.
     *
     * @var \DateTime|null
     *
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $publishedAt;

    /**
     * @var Taxonomy[]|ArrayCollection
     *
     * @ORM\ManyToMany(targetEntity="Taxonomy", inversedBy="events")
     * @ORM\JoinTable(name="events_taxonomies")
     */
    private $taxonomies;

    /**
     * @var int|null
     *
     * @ORM\ManyToOne(targetEntity="User")
     * @ORM\JoinColumn(name="created_by", referencedColumnName="id", onDelete="SET NULL")
     */
    private $createdBy;

    /**
     * @var int|null
     *
     * @ORM\ManyToOne(targetEntity="User")
     * @ORM\JoinColumn(name="updated_by", referencedColumnName="id", onDelete="SET NULL")
     */
    private $updatedBy;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $intervalle;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $periodicity;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $repetition_end_date;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $number_occurrence;

    /**
     * @var bool
     *
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $mass_modification;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $group_id;


    public function __construct()
    {
        $this->taxonomies = new ArrayCollection();
    }

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @return \DateTime
     */
    public function getBegin()
    {
        return $this->begin;
    }

    /**
     * @param \DateTime $begin
     *
     * @return $this
     */
    public function setBegin($begin): self
    {
        $this->begin = $begin;

        return $this;
    }

    /**
     * @return \DateTime|null
     */
    public function getEnd(): ?\DateTime
    {
        return $this->end;
    }

    /**
     * @param \DateTime|null $end
     *
     * @return $this
     */
    public function setEnd(?\DateTime $end): self
    {
        $this->end = $end;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getLink(): ?string
    {
        return $this->link;
    }

    /**
     * @param string|null $link
     *
     * @return $this
     */
    public function setLink(?string $link): self
    {
        $this->link = $link;

        return $this;
    }

    /**
     * @return bool|null
     */
    public function getIsPublished(): ?bool
    {
        return ($this->publishedAt <= DateTool::datetimeNow());
    }

    /**
     * @return \DateTime|null
     */
    public function getPublishedAt(): ?\DateTime
    {
        return $this->publishedAt;
    }

    /**
     * @param \DateTime|null $publishedAt
     *
     * @return $this
     */
    public function setPublishedAt(?\DateTime $publishedAt): self
    {
        $this->publishedAt = $publishedAt;

        return $this;
    }

    /**
     * @return Taxonomy[]|ArrayCollection
     */
    public function getTaxonomies()
    {
        return $this->taxonomies;
    }

    /**
     * @param Taxonomy $taxonomy
     *
     * @return $this
     */
    public function addTaxonomy(Taxonomy $taxonomy)
    {
        if (!$this->taxonomies->contains($taxonomy)) {
            $this->taxonomies->add($taxonomy);
        }
        return $this;
    }

    /**
     * @param Taxonomy $taxonomy
     *
     * @return $this
     */
    public function removeTaxonomy(Taxonomy $taxonomy)
    {
        if ($this->taxonomies->contains($taxonomy)) {
            $this->taxonomies->removeElement($taxonomy);
        }

        return $this;
    }

    public function getCreatedBy()
    {
        return $this->createdBy;
    }

    /**
     * @param $createdBy
     *
     * @return self
     */
    public function setCreatedBy($createdBy): self
    {
        $this->createdBy = $createdBy;

        return $this;
    }

    public function getUpdatedBy()
    {
        return $this->updatedBy;
    }

    /**
     * @param $updatedBy
     *
     * @return self
     */
    public function setUpdatedBy($updatedBy): self
    {
        $this->updatedBy = $updatedBy;

        return $this;
    }

    public function getIntervalle(): ?int
    {
        return $this->intervalle;
    }

    public function setIntervalle(?int $intervalle): self
    {
        $this->intervalle = $intervalle;

        return $this;
    }

    public function getPeriodicity(): ?string
    {
        return $this->periodicity;
    }

    public function setPeriodicity(?string $periodicity): self
    {
        $this->periodicity = $periodicity;

        return $this;
    }

    public function getRepetitionEndDate(): ?\DateTimeInterface
    {
        return $this->repetition_end_date;
    }

    public function setRepetitionEndDate(?\DateTimeInterface $repetition_end_date): self
    {
        $this->repetition_end_date = $repetition_end_date;

        return $this;
    }

    public function getNumberOccurrence(): ?int
    {
        return $this->number_occurrence;
    }

    public function setNumberOccurrence(?int $number_occurrence): self
    {
        $this->number_occurrence = $number_occurrence;

        return $this;
    }

    public function getMassModification(): ?bool
    {
        return $this->mass_modification;
    }

    public function setMassModification(?bool $mass_modification): self
    {
        $this->mass_modification = $mass_modification;

        return $this;
    }

    public function getGroupId(): ?string
    {
        return $this->group_id;
    }

    public function setGroupId(?string $group_id): self
    {
        $this->group_id = $group_id;

        return $this;
    }

    /* ############################################################## */
    /* ############# MAGIC METHODS USED BY TRANSLATIONS ############# */
    /* ############################################################## */

    public function getTitle()
    {
        return $this->proxyCurrentLocaleTranslation('getTitle');
    }

    public function getHook()
    {
        return $this->proxyCurrentLocaleTranslation('getHook');
    }

    public function getContent()
    {
        return $this->proxyCurrentLocaleTranslation('getContent');
    }

    public function getSlug()
    {
        return $this->proxyCurrentLocaleTranslation('getSlug');
    }

    /**
     * @return string
     */
    public function __toString()
    {
        $title = (string) $this->getTitle();

        if (empty($title)) {
            switch ($this->getCurrentLocale()) {
                case 'fr':
                    $title = $this->id . ' - Non traduit en français';
                    break;
                case 'en':
                    $title = $this->id . ' - Not translated in english';
                    break;
                default:
                    $title = $this->id . ' - Not translated at all';
                    break;
            }
        }

        return $title;
    }
}

src/Entity/Guide.php
<?php                                      
                                                     
namespace App\Entity;

use App\Contracts\TimestampableRdg\TimestampableRdgInterface;
use App\Contracts\TimestampableRdg\TimestampableRdgTrait;
use App\Validator as RdgAssert;
use Doctrine\Common\Collections\ArrayCollection;
use App\Repository\GuideRepository;
use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Contract\Entity\TranslatableInterface;
use Knp\DoctrineBehaviors\Model\Translatable\TranslatableTrait;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=GuideRepository::class)
 * @ORM\Table(name="guide")
 * @ORM\HasLifecycleCallbacks()
 * @Vich\Uploadable()
 *
 * @RdgAssert\Constraint\GuideConstraint()
 */
class Guide implements TranslatableInterface, TimestampableRdgInterface
{
    use TranslatableTrait;
    use TimestampableRdgTrait;

    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @Vich\UploadableField(mapping="guides", fileNameProperty="imageLocale")
     *
     * @Assert\File(
     *     maxSize="20M",
     *     mimeTypes={"image/png", "image/jpg", "image/jpeg", "image/x-png", "image/gif"}
     * )
     */
    private $imageFile;

    /**
     * @var CategoryGuide[]|ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="CategoryGuide", mappedBy="guide", cascade={"persist", "remove"}, orphanRemoval=true)
     */
    private $categories;

    /**
     * @var AdditionalHelpGuide[]|ArrayCollection
     *
     * @ORM\OneToMany(
     *     targetEntity="AdditionalHelpGuide",
     *     mappedBy="guide",
     *     cascade={"persist", "remove"},
     *     orphanRemoval=true
     * )
     */
    private $additionalHelps;

    /**
     * @var int|null
     *
     * @ORM\ManyToOne(targetEntity="User")
     * @ORM\JoinColumn(name="created_by", referencedColumnName="id", onDelete="SET NULL")
     */
    private $createdBy;

    /**
     * @var int|null
     *
     * @ORM\ManyToOne(targetEntity="User")
     * @ORM\JoinColumn(name="updated_by", referencedColumnName="id", onDelete="SET NULL")
     */
    private $updatedBy;


    public function __construct()
    {
        $this->categories = new ArrayCollection();
        $this->additionalHelps = new ArrayCollection();
    }

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * @param $image
     *
     * @return $this
     */
    public function setImage($image): self
    {
        $this->image = $image;

        return $this;
    }
    
    /**
     * @return mixed
     */
    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     * @param $imageFile
     *
     * @return $this
     */
    public function setImageFile($imageFile): self
    {
        $this->imageFile = $imageFile;

        // To force doctrine something changed on this entity.
        if ($imageFile) {
            $this->updatedAt = new \DateTime();
        }
        return $this;
    }

    /**
     * @return CategoryGuide[]|ArrayCollection
     */
    public function getCategories()
    {
        return $this->categories;
    }

    public function addCategory(CategoryGuide $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
            $category->setGuide($this);
        }

        return $this;
    }

    public function removeCategory(CategoryGuide $category): self
    {
        if ($this->categories->removeElement($category)) {
            // set the owning side to null (unless already changed)
            if ($category->getGuide() === $this) {
                $category->setGuide(null);
            }
        }

        return $this;
    }

    /**
     * @return AdditionalHelpGuide[]|ArrayCollection
     */
    public function getAdditionalHelps()
    {
        return $this->additionalHelps;
    }

    public function addAdditionalHelp(AdditionalHelpGuide $additionalHelp): self
    {
        if (!$this->additionalHelps->contains($additionalHelp)) {
            $this->additionalHelps[] = $additionalHelp;
            $additionalHelp->setGuide($this);
        }

        return $this;
    }

    public function removeAdditionalHelp(AdditionalHelpGuide $additionalHelp): self
    {
        if ($this->additionalHelps->removeElement($additionalHelp)) {
            // set the owning side to null (unless already changed)
            if ($additionalHelp->getGuide() === $this) {
                $additionalHelp->setGuide(null);
            }
        }

        return $this;
    }

    public function getCreatedBy()
    {
        return $this->createdBy;
    }

    /**
     * @param $createdBy
     *
     * @return $this
     */
    public function setCreatedBy($createdBy): self
    {
        $this->createdBy = $createdBy;

        return $this;
    }

    public function getUpdatedBy()
    {
        return $this->updatedBy;
    }

    /**
     * @param $updatedBy
     *
     * @return $this
     */
    public function setUpdatedBy($updatedBy): self
    {
        $this->updatedBy = $updatedBy;

        return $this;
    }

    /* ############################################################## */
    /* ############# SPECIAL GETTERS IN CURRENT LOCALE  ############# */
    /* ############################################################## */

    public function getTitle()
    {
        return $this->proxyCurrentLocaleTranslation('getTitle');
    }

    public function getContent()
    {
        return $this->proxyCurrentLocaleTranslation('getContent');
    }

    public function getSlug()
    {
        return $this->proxyCurrentLocaleTranslation('getSlug');
    }

    public function getImageLocale()
    {
        return $this->proxyCurrentLocaleTranslation('getImageLocale');
    }

    public function getimgLicence()
    {
        return $this->proxyCurrentLocaleTranslation('getImgLicence');
    }

    public function getImgLegend()
    {
        return $this->proxyCurrentLocaleTranslation('getImgLegend');
    }

    /**
     * @return string
     */
    public function __toString()
    {
        return (string)$this->getTitle();
    }
}

templates/partials/oneguide/_bannerpage.html.twig
{% if introBanner.isEnable %}
    {% include 'partials/common/_breadcrumbpages.html.twig' %}
    <div class="fr-container fr-pb-3w padding-body fr-mx-0 fr-mx-md-1w mx-lg-3">
        <div class="fr-grid-row">
            <div class="fr-col">
                <h1 class="fr-h1 actu-title-border fr-mb-2w">{{ introBanner.title }}</h1>
                <p class="fr-text fr-mt-2w">{{ introBanner.description|raw }}</p>
            </div>
        </div>
    </div>
{% else %}
    <div class="fr-pl-md-2w">
        {% include 'partials/common/_breadcrumbpages.html.twig' %}
    </div>
{% endif %}

templates/partials/oneguide/_mainoneguide.html.twig
<main class="fr-fluid" role="main">
    {% block main %}
        {% include 'partials/oneguide/_bannerpage.html.twig' %}
        {% block page %}
            {% include 'partials/oneguide/_oneguide.html.twig' %}
        {% endblock %}
        {% include 'partials/logigrams/_logigram.html.twig' %}
        {% include 'partials/common/_search-footer.html.twig' %}
    {% endblock %}
</main>

templates/partials/oneguide/_menuoneguide.html.twig
{% if guideMenu is defined and guideMenu is not empty %}
<nav class="fr-sidemenu fr-sidemenu--sticky-full-height" role="navigation" aria-label="{{ 'front.header.side.menu'|trans }}">
    <div class="fr-sidemenu__inner">
        <button class="fr-sidemenu__btn" aria-controls="fr-sidemenu-wrapper" aria-expanded="false" data-fr-js-collapse-button="true">{{ 'front.oneguide.menu'|trans }}</button>
         <div class="fr-collapse" id="fr-sidemenu-wrapper">
            <ul class="fr-sidemenu__list fr-pl-0">
            {% for items in guideMenu %}
                <li class="fr-sidemenu__item {{ items.selected ? 'fr-sidemenu__item--active' : '' }}">
                    <button class="fr-sidemenu__btn" aria-expanded="{{ items.selected ? 'true' : 'false' }}" aria-controls="fr-sidemenu-item-{{ loop.index0 }}" {{ items.selected ? 'aria-current="true"' : '' }}>{{ items.category }}</button>
                    <div class="fr-collapse" id="fr-sidemenu-item-{{ loop.index0 }}">
                        <ul class="fr-sidemenu__list fr-pl-0">
                        {% for itemGuide in items.guides|sort((a, b) => a.weight <=> b.weight) %}
                            <li class="fr-sidemenu__item {{ itemGuide.selected ? 'fr-sidemenu__item--active' : '' }}">
                                <a class="fr-sidemenu__link" href="{{ itemGuide.url }}" {{ itemGuide.selected ? 'aria-current="page"' : '' }} target="_self">{{ itemGuide.title }}</a>
                            </li>
                        {% endfor %}
                        </ul>
                    </div>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>
</nav>
{% endif %}

templates/partials/oneguide/_oneguide.html.twig
<div class="fr-fluid">
    <div class="fr-grid-row">
        <div class="fr-col-md-4 fr-col-sm-12">
            {% include 'partials/oneguide/_menuoneguide.html.twig' %}
        </div>
        <div class="fr-col-md-8 fr-col-sm-12">
            {% include 'partials/common/_printmenu.html.twig' %}
            <div id="print-area"> 
                <h1 class="fr-h1 actu-title-border fr-mb-1v">{{ entity.title }}</h1>
                <div class="fr-mt-2w">
                    {% if entity.imageLocale is not empty %}
                    <div class="fr-card__img">
                        <img src="{{ entity.imageLocale }}" class="fr-responsive-img" style="width: 100%" alt="{{ entity.title }}">
                    </div>
                        {% if entity.imgLicence or entity.imgLegend is not empty  %}
                            <div class="color-grey-666">
                                <figcaption>{{ entity.imgLegend }}</figcaption><small>{{ entity.imgLicence }}</small><br/>
                            </div>
                        {% endif %}
                    {% endif %}
                    <span class="fr-text--xs color-grey-666">{{ 'front.updatedAt'|trans }} {{ entity.updatedAt|date("d/m/Y") }}</span>
                    <div class="fr-my-4w">
                        {{ entity.content|raw }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="fr-fluid">
    {% include 'partials/oneguide/_seetoo.html.twig' %}
</div>

<!-- Hide page elements for print commands -->
<style type="text/css" media="print">
    .fr-header, .fr-container, .fr-sidemenu,
    .search-up-data, .fr-footer, .fr-footer__bottom,
    .backtotop, .print-input { display: none !important }
</style>

templates/partials/oneguide/_seetoo.html.twig
{% if seeMore is defined and seeMore is not empty %}
<div class="fr-container fr-mt-6w">
    <div class="bg-banner-guide">
        <div class="fr-grid-row fr-px-md-8w fr-px-1w">
            <div class="fr-col">
                <p class="fr-text--lg fw-bold fr-mt-md-7w fr-mt-3w fr-mb-3w fr-px-3v">{{ 'front.oneguide.seetoo'|trans }}</p>
            </div>
        </div>
        {% if seeMore|length > 2 and seeMore|length < 5 %}
            <div class="fr-grid-row fr-grid-row--gutters fr-px-md-8w fr-px-1w fr-pt-0 fr-mx-0 fr-pb-2w">
                {% for additionalHelp in seeMore|slice(0, 2) %}
                    <div class="fr-col-12 fr-col-lg">
                        <div class="fr-card fr-enlarge-link">
                            <div class="fr-card__body">
                                <h4 class="fr-card__title">
                                    <a href="{{ additionalHelp.link }}" class="fr-card__link">{{ additionalHelp.name }}</a>
                                </h4>
                                <p class="fr-card__desc">{{ additionalHelp.description|striptags|u.truncate(150, '...', false)|raw }}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="fr-grid-row fr-grid-row--gutters fr-px-md-8w fr-px-1w fr-pt-0 fr-mx-0 fr-pb-6w fr-mb-6w">
                {% for additionalHelp in seeMore[2:2] %}
                    <div class="fr-col-12 fr-col-lg">
                        <div class="fr-card fr-enlarge-link">
                            <div class="fr-card__body">
                                <h4 class="fr-card__title">
                                    <a href="{{ additionalHelp.link }}" class="fr-card__link">{{ additionalHelp.name }}</a>
                                </h4>
                                <p class="fr-card__desc">{{ additionalHelp.description|striptags|u.truncate(150, '...', false)|raw }}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% elseif seeMore|length > 2 and seeMore|length > 4 %}
            <div class="fr-grid-row fr-grid-row--gutters fr-px-md-8w fr-px-1w fr-pt-0 fr-mx-0 fr-pb-2w">
                {% for additionalHelp in seeMore|slice(0, 2) %}
                    <div class="fr-col-12 fr-col-lg">
                        <div class="fr-card fr-enlarge-link">
                            <div class="fr-card__body">
                                <h4 class="fr-card__title">
                                    <a href="{{ additionalHelp.link }}" class="fr-card__link">{{ additionalHelp.name }}</a>
                                </h4>
                                <p class="fr-card__desc">{{ additionalHelp.description|striptags|u.truncate(150, '...', false)|raw }}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="fr-grid-row fr-grid-row--gutters fr-px-md-8w fr-px-1w fr-pt-0 fr-mx-0 fr-pb-2w">
                {% for additionalHelp in seeMore[2:2] %}
                    <div class="fr-col-12 fr-col-lg">
                        <div class="fr-card fr-enlarge-link">
                            <div class="fr-card__body">
                                <h4 class="fr-card__title">
                                    <a href="{{ additionalHelp.link }}" class="fr-card__link">{{ additionalHelp.name }}</a>
                                </h4>
                                <p class="fr-card__desc">{{ additionalHelp.description|striptags|u.truncate(150, '...', false)|raw }}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="fr-grid-row fr-grid-row--gutters fr-px-md-8w fr-px-1w fr-pt-0 fr-mx-0 fr-pb-6w fr-mb-6w">
                {% for additionalHelp in seeMore[4:2] %}
                    <div class="fr-col-12 fr-col-lg">
                        <div class="fr-card fr-enlarge-link">
                            <div class="fr-card__body">
                                <h4 class="fr-card__title">
                                    <a href="{{ additionalHelp.link }}" class="fr-card__link">{{ additionalHelp.name }}</a>
                                </h4>
                                <p class="fr-card__desc">{{ additionalHelp.description|striptags|u.truncate(150, '...', false)|raw }}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <div class="fr-grid-row fr-grid-row--gutters fr-px-md-8w fr-px-1w fr-pt-0 fr-mx-0 fr-pb-6w fr-mb-6w">
                {% for additionalHelp in seeMore %}
                <div class="fr-col-12 fr-col-lg">
                    <div class="fr-card fr-enlarge-link">
                        <div class="fr-card__body">
                            <h4 class="fr-card__title">
                                <a href="{{ additionalHelp.link }}" class="fr-card__link">{{ additionalHelp.name }}</a>
                            </h4>
                            <p class="fr-card__desc">{{ additionalHelp.description|striptags|u.truncate(150, '...', false)|raw }}</p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>
</div>
{% endif %}