src/Entity/Event.php
<?php                                      
                                                     
namespace App\Entity;

use App\Contracts\TimestampableRdg\TimestampableRdgInterface;
use App\Contracts\TimestampableRdg\TimestampableRdgTrait;
use App\Repository\EventRepository;
use App\Tool\DateTool;
use App\Validator as RdgAssert;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Contract\Entity\TranslatableInterface;
use Knp\DoctrineBehaviors\Model\Translatable\TranslatableTrait;

/**
 * @ORM\Entity(repositoryClass=EventRepository::class)
 * @ORM\Table(name="event")
 * @ORM\HasLifecycleCallbacks()
 *
 * @RdgAssert\Constraint\EventConstraint()
 */
class Event implements TranslatableInterface, TimestampableRdgInterface
{
    use TranslatableTrait;
    use TimestampableRdgTrait;

    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var \DateTime
     *
     * @ORM\Column(type="datetime")
     */
    private $begin;

    /**
     * @var \DateTime|null
     *
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $end;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255)
     */
    private $link;

    /**
     * Publication is manually control and can be schedule.
     *
     * @var \DateTime|null
     *
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $publishedAt;

    /**
     * @var Taxonomy[]|ArrayCollection
     *
     * @ORM\ManyToMany(targetEntity="Taxonomy", inversedBy="events")
     * @ORM\JoinTable(name="events_taxonomies")
     */
    private $taxonomies;

    /**
     * @var int|null
     *
     * @ORM\ManyToOne(targetEntity="User")
     * @ORM\JoinColumn(name="created_by", referencedColumnName="id", onDelete="SET NULL")
     */
    private $createdBy;

    /**
     * @var int|null
     *
     * @ORM\ManyToOne(targetEntity="User")
     * @ORM\JoinColumn(name="updated_by", referencedColumnName="id", onDelete="SET NULL")
     */
    private $updatedBy;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $intervalle;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $periodicity;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $repetition_end_date;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $number_occurrence;

    /**
     * @var bool
     *
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $mass_modification;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $group_id;


    public function __construct()
    {
        $this->taxonomies = new ArrayCollection();
    }

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @return \DateTime
     */
    public function getBegin()
    {
        return $this->begin;
    }

    /**
     * @param \DateTime $begin
     *
     * @return $this
     */
    public function setBegin($begin): self
    {
        $this->begin = $begin;

        return $this;
    }

    /**
     * @return \DateTime|null
     */
    public function getEnd(): ?\DateTime
    {
        return $this->end;
    }

    /**
     * @param \DateTime|null $end
     *
     * @return $this
     */
    public function setEnd(?\DateTime $end): self
    {
        $this->end = $end;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getLink(): ?string
    {
        return $this->link;
    }

    /**
     * @param string|null $link
     *
     * @return $this
     */
    public function setLink(?string $link): self
    {
        $this->link = $link;

        return $this;
    }

    /**
     * @return bool|null
     */
    public function getIsPublished(): ?bool
    {
        return ($this->publishedAt <= DateTool::datetimeNow());
    }

    /**
     * @return \DateTime|null
     */
    public function getPublishedAt(): ?\DateTime
    {
        return $this->publishedAt;
    }

    /**
     * @param \DateTime|null $publishedAt
     *
     * @return $this
     */
    public function setPublishedAt(?\DateTime $publishedAt): self
    {
        $this->publishedAt = $publishedAt;

        return $this;
    }

    /**
     * @return Taxonomy[]|ArrayCollection
     */
    public function getTaxonomies()
    {
        return $this->taxonomies;
    }

    /**
     * @param Taxonomy $taxonomy
     *
     * @return $this
     */
    public function addTaxonomy(Taxonomy $taxonomy)
    {
        if (!$this->taxonomies->contains($taxonomy)) {
            $this->taxonomies->add($taxonomy);
        }
        return $this;
    }

    /**
     * @param Taxonomy $taxonomy
     *
     * @return $this
     */
    public function removeTaxonomy(Taxonomy $taxonomy)
    {
        if ($this->taxonomies->contains($taxonomy)) {
            $this->taxonomies->removeElement($taxonomy);
        }

        return $this;
    }

    public function getCreatedBy()
    {
        return $this->createdBy;
    }

    /**
     * @param $createdBy
     *
     * @return self
     */
    public function setCreatedBy($createdBy): self
    {
        $this->createdBy = $createdBy;

        return $this;
    }

    public function getUpdatedBy()
    {
        return $this->updatedBy;
    }

    /**
     * @param $updatedBy
     *
     * @return self
     */
    public function setUpdatedBy($updatedBy): self
    {
        $this->updatedBy = $updatedBy;

        return $this;
    }

    public function getIntervalle(): ?int
    {
        return $this->intervalle;
    }

    public function setIntervalle(?int $intervalle): self
    {
        $this->intervalle = $intervalle;

        return $this;
    }

    public function getPeriodicity(): ?string
    {
        return $this->periodicity;
    }

    public function setPeriodicity(?string $periodicity): self
    {
        $this->periodicity = $periodicity;

        return $this;
    }

    public function getRepetitionEndDate(): ?\DateTimeInterface
    {
        return $this->repetition_end_date;
    }

    public function setRepetitionEndDate(?\DateTimeInterface $repetition_end_date): self
    {
        $this->repetition_end_date = $repetition_end_date;

        return $this;
    }

    public function getNumberOccurrence(): ?int
    {
        return $this->number_occurrence;
    }

    public function setNumberOccurrence(?int $number_occurrence): self
    {
        $this->number_occurrence = $number_occurrence;

        return $this;
    }

    public function getMassModification(): ?bool
    {
        return $this->mass_modification;
    }

    public function setMassModification(?bool $mass_modification): self
    {
        $this->mass_modification = $mass_modification;

        return $this;
    }

    public function getGroupId(): ?string
    {
        return $this->group_id;
    }

    public function setGroupId(?string $group_id): self
    {
        $this->group_id = $group_id;

        return $this;
    }

    /* ############################################################## */
    /* ############# MAGIC METHODS USED BY TRANSLATIONS ############# */
    /* ############################################################## */

    public function getTitle()
    {
        return $this->proxyCurrentLocaleTranslation('getTitle');
    }

    public function getHook()
    {
        return $this->proxyCurrentLocaleTranslation('getHook');
    }

    public function getContent()
    {
        return $this->proxyCurrentLocaleTranslation('getContent');
    }

    public function getSlug()
    {
        return $this->proxyCurrentLocaleTranslation('getSlug');
    }

    /**
     * @return string
     */
    public function __toString()
    {
        $title = (string) $this->getTitle();

        if (empty($title)) {
            switch ($this->getCurrentLocale()) {
                case 'fr':
                    $title = $this->id . ' - Non traduit en français';
                    break;
                case 'en':
                    $title = $this->id . ' - Not translated in english';
                    break;
                default:
                    $title = $this->id . ' - Not translated at all';
                    break;
            }
        }

        return $title;
    }
}

src/Entity/Lame/NewsLame.php
<?php                                      
                                                     
namespace App\Entity\Lame;

use App\Contracts\TimestampableRdg\TimestampableRdgInterface;
use App\Contracts\TimestampableRdg\TimestampableRdgTrait;
use App\Entity\Actuality;
use App\Entity\Event;
use App\Validator as RdgAssert;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Contract\Entity\TranslatableInterface;
use Knp\DoctrineBehaviors\Model\Translatable\TranslatableTrait;

/**
 * @ORM\Entity(repositoryClass="App\Repository\Lame\NewsLameRepository")
 * @ORM\Table(name="lame_news")
 *
 * @RdgAssert\Constraint\LaminaConstraint()
 */
class NewsLame extends Lame implements TranslatableInterface, TimestampableRdgInterface
{
    use TranslatableTrait;
    use TimestampableRdgTrait;

    public const NB_NEWS = 3;
    public const NB_EVENTS = 3;

    /**
     * @var bool
     *
     * @ORM\Column(type="boolean", nullable=false)
     */
    private $autoActu = false;

    /**
     * @var bool
     *
     * @ORM\Column(type="boolean", nullable=false)
     */
    private $autoEvent = false;

    /**
     * @var Actuality[]|ArrayCollection
     */
    private $actualities;

    /**
     * @var Event|ArrayCollection
     */
    private $events;

    /**
     * @var Actuality|null
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Actuality")
     * @ORM\JoinColumn(name="actu_first", referencedColumnName="id", onDelete="SET NULL")
     */
    private $actuFirst = null;

    /**
     * @var Actuality|null
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Actuality")
     * @ORM\JoinColumn(name="actu_second", referencedColumnName="id", onDelete="SET NULL")
     */
    private $actuSecond = null;

    /**
     * @var Actuality|null
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Actuality")
     * @ORM\JoinColumn(name="actu_third", referencedColumnName="id", onDelete="SET NULL")
     */
    private $actuThird = null;

    /**
     * @var Actuality|null
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Actuality")
     * @ORM\JoinColumn(name="actu_fourth", referencedColumnName="id", onDelete="SET NULL")
     */
    private $actuFourth = null;

    /**
     * @var Event|null
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Event")
     * @ORM\JoinColumn(name="event_first", referencedColumnName="id", onDelete="SET NULL")
     */
    private $eventFirst = null;

    /**
     * @var Event|null
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Event")
     * @ORM\JoinColumn(name="event_second", referencedColumnName="id", onDelete="SET NULL")
     */
    private $eventSecond = null;

    /**
     * @var Event|null
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Event")
     * @ORM\JoinColumn(name="event_third", referencedColumnName="id", onDelete="SET NULL")
     */
    private $eventThird = null;

    /**
     * @var Event|null
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Event")
     * @ORM\JoinColumn(name="event_fourth", referencedColumnName="id", onDelete="SET NULL")
     */
    private $eventFourth = null;

    /**
     * @var Event|null
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Event")
     * @ORM\JoinColumn(name="event_fifth", referencedColumnName="id", onDelete="SET NULL")
     */
    private $eventFifth = null;

    public function __construct()
    {
        $this->actualities = new ArrayCollection();
        $this->events = new ArrayCollection();
    }

    /**
     * @return bool
     */
    public function getAutoActu(): bool
    {
        return $this->autoActu;
    }

    /**
     * @param bool $autoActu
     *
     * @return $this
     */
    public function setAutoActu(bool $autoActu): self
    {
        $this->autoActu = $autoActu;

        return $this;
    }

    /**
     * @return bool
     */
    public function getAutoEvent(): bool
    {
        return $this->autoEvent;
    }

    /**
     * @param bool $autoEvent
     *
     * @return $this
     */
    public function setAutoEvent(bool $autoEvent): self
    {
        $this->autoEvent = $autoEvent;

        return $this;
    }

    /**
     * @return Actuality[]|ArrayCollection
     */
    public function getActualities()
    {
        return $this->actualities;
    }

    /**
     * @param Actuality[]|ArrayCollection $actualities
     *
     * @return $this
     */
    public function setActualities($actualities): self
    {
        $this->actualities = $actualities;

        return $this;
    }

    /**
     * @return Event|ArrayCollection
     */
    public function getEvents()
    {
        return $this->events;
    }

    /**
     * @param Event|ArrayCollection $events
     *
     * @return $this
     */
    public function setEvents($events): self
    {
        $this->events = $events;

        return $this;
    }

    /**
     * @return Actuality|null
     */
    public function getActuFirst(): ?Actuality
    {
        return $this->actuFirst;
    }

    /**
     * @param Actuality|null $actuFirst
     *
     * @return $this
     */
    public function setActuFirst(?Actuality $actuFirst): self
    {
        $this->actuFirst = $actuFirst;

        return $this;
    }

    /**
     * @return Actuality|null
     */
    public function getActuSecond(): ?Actuality
    {
        return $this->actuSecond;
    }

    /**
     * @param Actuality|null $actuSecond
     *
     * @return $this
     */
    public function setActuSecond(?Actuality $actuSecond): self
    {
        $this->actuSecond = $actuSecond;

        return $this;
    }

    /**
     * @return Actuality|null
     */
    public function getActuThird(): ?Actuality
    {
        return $this->actuThird;
    }

    /**
     * @param Actuality|null $actuThird
     *
     * @return $this
     */
    public function setActuThird(?Actuality $actuThird): self
    {
        $this->actuThird = $actuThird;

        return $this;
    }

    /**
     * @return Actuality|null
     */
    public function getActuFourth(): ?Actuality
    {
        return $this->actuFourth;
    }

    /**
     * @param Actuality|null $actuFourth
     *
     * @return $this
     */
    public function setActuFourth(?Actuality $actuFourth): self
    {
        $this->actuFourth = $actuFourth;

        return $this;
    }

    /**
     * @return Event|null
     */
    public function getEventFirst(): ?Event
    {
        return $this->eventFirst;
    }

    /**
     * @param Event|null $eventFirst
     *
     * @return $this
     */
    public function setEventFirst(?Event $eventFirst): self
    {
        $this->eventFirst = $eventFirst;

        return $this;
    }

    /**
     * @return Event|null
     */
    public function getEventSecond(): ?Event
    {
        return $this->eventSecond;
    }

    /**
     * @param Event|null $eventSecond
     *
     * @return $this
     */
    public function setEventSecond(?Event $eventSecond): self
    {
        $this->eventSecond = $eventSecond;

        return $this;
    }

    /**
     * @return Event|null
     */
    public function getEventThird(): ?Event
    {
        return $this->eventThird;
    }

    /**
     * @param Event|null $eventThird
     *
     * @return $this
     */
    public function setEventThird(?Event $eventThird): self
    {
        $this->eventThird = $eventThird;

        return $this;
    }

    /**
     * @return Event|null
     */
    public function getEventFourth(): ?Event
    {
        return $this->eventFourth;
    }

    /**
     * @param Event|null $eventFourth
     *
     * @return $this
     */
    public function setEventFourth(?Event $eventFourth): self
    {
        $this->eventFourth = $eventFourth;

        return $this;
    }

    /**
     * @return Event|null
     */
    public function getEventFifth(): ?Event
    {
        return $this->eventFifth;
    }

    /**
     * @param Event|null $eventFifth
     *
     * @return $this
     */
    public function setEventFifth(?Event $eventFifth): self
    {
        $this->eventFifth = $eventFifth;

        return $this;
    }

    /* ############################################################## */
    /* ############# SPECIAL GETTERS IN CURRENT LOCALE  ############# */
    /* ############################################################## */

    public function getTitle()
    {
        return $this->proxyCurrentLocaleTranslation('getTitle');
    }

    /**
     * @return string
     */
    public function __toString()
    {
        return (string)$this->getTitle();
    }
}

templates/bundles/EasyAdminBundle/lame/list.html.twig
{% extends 'bundles/EasyAdminBundle/layout.html.twig' %}

{% block content_title %}
    {{ 'content.lames'|trans|capitalize }}
{% endblock %}

{% block main %}

    <section>
    {% include 'bundles/EasyAdminBundle/lame/select.html.twig' %}
    </section>

    <hr>

    <section>
    <table class="table datagrid">
        {% if lames is iterable %}
        <thead>
        <tr>
            <th class="field-virtual header-for-field-text text-left"><span>{{ 'lame.prop.title'|trans|capitalize }}</span></th>
            <th class="field-virtual header-for-field-text text-left"><span>{{ 'lame.prop.type'|trans|capitalize }}</span></th>
            <th class="field-virtual header-for-field-boolean text-left"><span>{{ 'lame.prop.isPublished'|trans|capitalize }}</span></th>
            <th class="field-virtual header-for-field-text text-left"><span>{{ 'prop.weight'|trans|capitalize }}</span></th>
            <th class="header-for-field-datetime text-left"><span>{{ 'prop.publishedAt'|trans|capitalize }}</span></th>
            <th class="header-for-field-datetime text-left"><span>{{ 'prop.createdAt'|trans|capitalize }}</span></th>
            <th class="header-for-field-datetime text-left"><span>{{ 'prop.updatedAt'|trans|capitalize }}</span></th>
            <th class="field-virtual header-for-field-text text-left"><span>{{ 'prop.createdBy'|trans|capitalize }}</span></th>
            <th class="field-virtual header-for-field-text text-left"><span>{{ 'prop.updatedBy'|trans|capitalize }}</span></th>
            <th width="10px" dir="ltr"></th>
        </tr>
        </thead>
        <tbody>
        {% for  lame in lames %}
            <tr>
                <td data-label="title">
                    {% if  lame.title is empty %}
                        <span class="badge badge-secondary">{{ 'label.null'|trans(domain = 'EasyAdminBundle') }}</span>
                    {% else %}
                        {{ lame.title }}
                    {% endif %}
                </td>
                <td data-label="type">{{ lame.type|trans }}</td>
                <td data-label="isPublished">{{ lame.isPublished ? 'bo.yes'|trans : 'bo.no'|trans }}</td>
                <td data-label="weight">{{ lame.weight }}</td>
                <td data-label="publishedAt">{{ lame.publishedAt|format_datetime(locale=app.request.locale) }}</td>
                <td data-label="createdAt">{{ lame.createdAt|format_datetime(locale=app.request.locale) }}</td>
                <td data-label="updatedAt">{{ lame.updatedAt|format_datetime(locale=app.request.locale) }}</td>
                <td data-label="createdBy">{{ lame.createdBy }}</td>
                <td data-label="updatedBy">{{ lame.updatedBy }}</td>
                <td class="actions">
                    <div class="dropdown dropdown-actions">
                        <a class="dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {# don't use FontAwesome 'fa-ellipsis-h' icon here because it doesn't look good #}
                            {# this icon is 'dots-horizontal' icon from https://heroicons.com/ #}
                            <svg xmlns="http://www.w3.org/2000/svg" height="21" width="21" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 12h.01M12 12h.01M19 12h.01M6 12a1 1 0 11-2 0 1 1 0 012 0zm7 0a1 1 0 11-2 0 1 1 0 012 0zm7 0a1 1 0 11-2 0 1 1 0 012 0z" />
                            </svg>
                        </a>

                        <div class="dropdown-menu dropdown-menu-right">
                            <a class="dropdown-item action-edit"
                               href="{{ lame.edit }}"
                               data-action-name="edit"
                            >
                                {{ 'bo.edit'|trans|capitalize }}
                            </a>
                            <a class="dropdown-item action-delete text-danger"
                               href="{{ lame.del }}"
                               data-bs-toggle="modal" data-bs-target="#modal-delete" data-action-name="delete"
                               formaction="{{ lame.del }}"
                            >
                                {{ 'bo.del'|trans|capitalize }}
                            </a>
                        </div>
                    </div>

                </td>
            </tr>
        {% endfor %}
        </tbody>

        {% else %}
            <tr class="no-results">
                <td colspan="100">
                    {{ 'datagrid.no_results'|trans(ea.i18n.translationParameters, 'EasyAdminBundle') }}
                </td>
            </tr>
        {% endif %}
    </table>

    {% include 'bundles/EasyAdminBundle/_delete_form.html.twig' %}

    </section>

{% endblock %}

{% block body_javascript %}
    <script>
        document.addEventListener('DOMContentLoaded', () => {
            createModalWindowsForDeleteActions();
        });
        const delRoute = createModalWindowsForDeleteActions {
            document.querySelectorAll('.action-delete').forEach((actionElement) => {
                actionElement.addEventListener('click', (event) => {
                    event.preventDefault();
                    document.querySelector('#modal-delete-button').addEventListener('click', () => {
                        const deleteFormAction = actionElement.getAttribute('formaction');
                        const deleteForm = document.querySelector('#delete-form');
                        deleteForm.setAttribute('action', deleteFormAction);
                        deleteForm.submit();
                    });
                });
            });
        }

    </script>
{% endblock body_javascript %}

templates/bundles/EasyAdminBundle/lame/select.html.twig
<div class="row row-cols-12">
    <div class="col-md-6">
        {{ 'form.lam.support'|trans|raw }}
    </div>
    <div class="col-md-6">
        <h4>{{ 'form.lame.add'|trans|capitalize }}</h4>
        {% form_theme selectForm 'bootstrap_4_layout.html.twig' %}
        {{ form_start(selectForm, {'method': 'POST'}) }}

        <div class="form-row align-items-center">
            <div class="col-auto my-1">
                {{ form_widget(selectForm.type, {'attr': {'class': 'custom-select mr-sm-2'}}) }}
            </div>
            <input type="hidden" name="_token" value="{{ csrf_token('lame') }}"/>
            <div class="col-auto my-1">
                <button type="submit" class="btn btn-info">{{ 'bo.next'|trans }}</button>
            </div>
        </div>

        {{ form_end(selectForm) }}
    </div>

</div>