src/Entity/Guide.php
<?php                                      
                                                     
namespace App\Entity;

use App\Contracts\TimestampableRdg\TimestampableRdgInterface;
use App\Contracts\TimestampableRdg\TimestampableRdgTrait;
use App\Validator as RdgAssert;
use Doctrine\Common\Collections\ArrayCollection;
use App\Repository\GuideRepository;
use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Contract\Entity\TranslatableInterface;
use Knp\DoctrineBehaviors\Model\Translatable\TranslatableTrait;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=GuideRepository::class)
 * @ORM\Table(name="guide")
 * @ORM\HasLifecycleCallbacks()
 * @Vich\Uploadable()
 *
 * @RdgAssert\Constraint\GuideConstraint()
 */
class Guide implements TranslatableInterface, TimestampableRdgInterface
{
    use TranslatableTrait;
    use TimestampableRdgTrait;

    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @Vich\UploadableField(mapping="guides", fileNameProperty="imageLocale")
     *
     * @Assert\File(
     *     maxSize="20M",
     *     mimeTypes={"image/png", "image/jpg", "image/jpeg", "image/x-png", "image/gif"}
     * )
     */
    private $imageFile;

    /**
     * @var CategoryGuide[]|ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="CategoryGuide", mappedBy="guide", cascade={"persist", "remove"}, orphanRemoval=true)
     */
    private $categories;

    /**
     * @var AdditionalHelpGuide[]|ArrayCollection
     *
     * @ORM\OneToMany(
     *     targetEntity="AdditionalHelpGuide",
     *     mappedBy="guide",
     *     cascade={"persist", "remove"},
     *     orphanRemoval=true
     * )
     */
    private $additionalHelps;

    /**
     * @var int|null
     *
     * @ORM\ManyToOne(targetEntity="User")
     * @ORM\JoinColumn(name="created_by", referencedColumnName="id", onDelete="SET NULL")
     */
    private $createdBy;

    /**
     * @var int|null
     *
     * @ORM\ManyToOne(targetEntity="User")
     * @ORM\JoinColumn(name="updated_by", referencedColumnName="id", onDelete="SET NULL")
     */
    private $updatedBy;


    public function __construct()
    {
        $this->categories = new ArrayCollection();
        $this->additionalHelps = new ArrayCollection();
    }

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * @param $image
     *
     * @return $this
     */
    public function setImage($image): self
    {
        $this->image = $image;

        return $this;
    }
    
    /**
     * @return mixed
     */
    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     * @param $imageFile
     *
     * @return $this
     */
    public function setImageFile($imageFile): self
    {
        $this->imageFile = $imageFile;

        // To force doctrine something changed on this entity.
        if ($imageFile) {
            $this->updatedAt = new \DateTime();
        }
        return $this;
    }

    /**
     * @return CategoryGuide[]|ArrayCollection
     */
    public function getCategories()
    {
        return $this->categories;
    }

    public function addCategory(CategoryGuide $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
            $category->setGuide($this);
        }

        return $this;
    }

    public function removeCategory(CategoryGuide $category): self
    {
        if ($this->categories->removeElement($category)) {
            // set the owning side to null (unless already changed)
            if ($category->getGuide() === $this) {
                $category->setGuide(null);
            }
        }

        return $this;
    }

    /**
     * @return AdditionalHelpGuide[]|ArrayCollection
     */
    public function getAdditionalHelps()
    {
        return $this->additionalHelps;
    }

    public function addAdditionalHelp(AdditionalHelpGuide $additionalHelp): self
    {
        if (!$this->additionalHelps->contains($additionalHelp)) {
            $this->additionalHelps[] = $additionalHelp;
            $additionalHelp->setGuide($this);
        }

        return $this;
    }

    public function removeAdditionalHelp(AdditionalHelpGuide $additionalHelp): self
    {
        if ($this->additionalHelps->removeElement($additionalHelp)) {
            // set the owning side to null (unless already changed)
            if ($additionalHelp->getGuide() === $this) {
                $additionalHelp->setGuide(null);
            }
        }

        return $this;
    }

    public function getCreatedBy()
    {
        return $this->createdBy;
    }

    /**
     * @param $createdBy
     *
     * @return $this
     */
    public function setCreatedBy($createdBy): self
    {
        $this->createdBy = $createdBy;

        return $this;
    }

    public function getUpdatedBy()
    {
        return $this->updatedBy;
    }

    /**
     * @param $updatedBy
     *
     * @return $this
     */
    public function setUpdatedBy($updatedBy): self
    {
        $this->updatedBy = $updatedBy;

        return $this;
    }

    /* ############################################################## */
    /* ############# SPECIAL GETTERS IN CURRENT LOCALE  ############# */
    /* ############################################################## */

    public function getTitle()
    {
        return $this->proxyCurrentLocaleTranslation('getTitle');
    }

    public function getContent()
    {
        return $this->proxyCurrentLocaleTranslation('getContent');
    }

    public function getSlug()
    {
        return $this->proxyCurrentLocaleTranslation('getSlug');
    }

    public function getImageLocale()
    {
        return $this->proxyCurrentLocaleTranslation('getImageLocale');
    }

    public function getimgLicence()
    {
        return $this->proxyCurrentLocaleTranslation('getImgLicence');
    }

    public function getImgLegend()
    {
        return $this->proxyCurrentLocaleTranslation('getImgLegend');
    }

    /**
     * @return string
     */
    public function __toString()
    {
        return (string)$this->getTitle();
    }
}

src/Controller/Front/ContactController.php
<?php                                      
                                                     
namespace App\Controller\Front;

use App\Entity\Subject;
use App\Entity\SubjectTranslation;
use App\Form\Front\ContactSubjectType;
use App\Service\FooterService;
use App\Service\HeaderService;
use Doctrine\ORM\EntityManagerInterface;
use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\Exception\TransportExceptionInterface;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

/**
 * Front controller to manage contact forms.
 */
class ContactController extends AbstractController
{
    /**
     * Default subject to use if none has been chosen.
     *
     */
    public const NONE_SUBJECT = "Message RDG Contact";

    /**
     * To get links to Page entities and SocialNetwork entities in footer.
     *
     * @var FooterService
     */
    protected FooterService $footerService;

    /**
     * @var HeaderService
     */
    protected HeaderService $headerService;

    /**
     * @var TranslatorInterface
     */
    private TranslatorInterface $translator;

    /**
     * @param FooterService       $footerService
     * @param HeaderService       $headerService
     * @param TranslatorInterface $translator
     */
    public function __construct(
        FooterService $footerService,
        HeaderService $headerService,
        TranslatorInterface $translator
    ) {
        $this->footerService = $footerService;
        $this->headerService = $headerService;
        $this->translator = $translator;
    }

    /**
     * Get data from Contact Form then send it.
     *
     * @Route({
     *     "fr" : "/fr/contact",
     *     "en" : "/en/contact"
     * }, name="front.contact")
     *
     * @param Request         $request
     * @param MailerInterface $mailer
     * @param LoggerInterface $logger
     *
     * @return Response
     *
     * @throws TransportExceptionInterface
     */
    public function contact(Request $request, MailerInterface $mailer, LoggerInterface $logger, EntityManagerInterface $em): Response
    {
        $locale = $request->getLocale();
        $form = $this->createForm(ContactSubjectType::class);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $contactFormData = $form->getData();
            if (isset($contactFormData['ref']) && !empty($contactFormData['ref'])) {
                $logger->alert(
                    sprintf(
                        'Spam tried with %s from %s',
                        $contactFormData['email'],
                        $request->getClientIp()
                    )
                );

                return $this->returnForm($form, $locale);
            }
            $subject = (string) $contactFormData['subject'];
            $recipients = $this->getRecipients($request, $subject, $em);
            if (empty($subject)) {
                $subject = self::NONE_SUBJECT;
            }

            $text = 'Un message a été envoyé de ' . $contactFormData['email']
                . PHP_EOL . PHP_EOL .
                    $this->translator->trans('contact.label.other') . ':' . PHP_EOL . $contactFormData['other'] 
                . PHP_EOL . PHP_EOL . 'Votre message :' . PHP_EOL . $contactFormData['message'];
            $message = (new Email())
                ->replyTo($contactFormData['email'])
                ->from($this->getParameter('email_from'))
                //->to($this->getParameter('email_to'))
                ->to(...$recipients)
                ->subject($subject)
                ->text($text, 'text/plain');
            try {
                $mailer->send($message);
                $this->addFlash('success', $this->translator->trans('contact.sending.success'));
            } catch (\Exception $e) {
                $logger->critical('Issue with email sending...' . PHP_EOL . $e->getMessage());
                $this->addFlash('error', $this->translator->trans('contact.sending.error'));
            }

            return $this->redirectToRoute('front.contact');
        }

        return $this->returnForm($form, $locale);
    }

    /**
     * @param FormInterface $form
     * @param string        $locale
     *
     * @return Response
     */
    private function returnForm(Forminterface $form, string $locale): Response
    {
        return $this->render('contact.html.twig', [
            'contactForm' => $form->createView(),
            'breadcrumbs' => $this->headerService->generateBreadcrumbs(
                'contact',
                $locale
            ),
            'introBanner' => $this->headerService->getIntroBanner('front.contact', $locale),
            'headerDatas' => $this->headerService->getMainMenu($locale),
            'footerDatas' => $this->footerService->getLinksAndNetworks($locale),
            'switcherLng' => $this->headerService->getSwitcherSystem('front.contact'),
        ]);
    }

    private function getRecipients($request, $subject, $em) {
        $locale = $request->getLocale();
        $repository = $em->getRepository(SubjectTranslation::class);
        $subjectTranslation = $repository->findOneBy(['subject' => $subject]);
        $oSubject = $subjectTranslation->getTranslatable();
        $recipients = $oSubject->getRecipients();
        $tRecipient = [];
        foreach($recipients as $recipient){
            $tRecipient[] = $recipient->getEmail();
        }
        return $tRecipient;
    }
}

templates/partials/contact/_bannercontact.html.twig
{% if introBanner.isEnable %} 
    <div class="container-fluid d-flex flex-column align-items-center">
        {% include 'partials/common/_breadcrumbpages.html.twig' %}
        <h1 class="text-center txt-color fr-col-10 fw-bold">{{ introBanner.title }}</h1>
        <p class="text-center fr-col-10 fr-col-lg-6">{{ introBanner.description|raw }}</p>
    </div>
{% else %}
    <div class="fr-pl-md-2w">
        {% include 'partials/common/_breadcrumbpages.html.twig' %}
    </div>
    <div class="fr-container fr-pb-3w padding-body fr-mx-0 fr-mx-md-3w">
        <div class="fr-grid-row justify-content-center">
            <div class="fr-col-lg-6 fr-col-12">
                <h1 class="fr-h1 actu-title-border fr-mb-1v">{{ 'front.footer.contact'|trans }}</h1>
            </div>
        </div>
    </div>
{% endif %}

templates/partials/contact/_contact.html.twig
<div class="fr-container fr-pt-2w">
    <div class="fr-grid-row fr-grid-row--center fr-grid-row--gutters">
        <div class="fr-col-lg-6 fr-col-10 fr-pb-2w">
            {% set subjectParam = requestURI|last %}
            {% set contactFormOk = app.flashes('success') %}
            {% set contactFormKo = app.flashes('error') %}

            {% if contactFormOk|length > 0 %}

                {% for message in contactFormOk %}
                    <div role="alert" class="fr-alert fr-alert--success" style="margin-bottom: 2rem;">
                        <p>{{ message }}</p>
                    </div>
                {% endfor %}

            {% else %}

                {% for message in contactFormKo %}
                    <div role="alert" class="fr-alert fr-alert--error" style="margin-bottom: 2rem;">
                        <p>{{ message }}</p>
                    </div>
                {% endfor %}
                
                <p class="fr-text--sm fr-pb-2w">
                    <span class="fr-fi-error-warning-line fr-fi--sm" aria-hidden="true"></span>
                    <span style="color:red;">{{ 'contact.field.required'|trans }}</span>
                </p>
                
                {{ form_start(contactForm, {'method': 'POST', 'attr': {'novalidate': 'novalidate', 'id': 'contactform' }}) }}                
                
                {% if 'subject=eventSuggest' in subjectParam %}
                    <div class="fr-input-group">
                        <div class="fr-select-group">
                            {{ form_label(contactForm.subject, '', {
                                'label_attr': {'class': 'fr-label'}
                            }) }}
                            {{ form_widget(contactForm.subject, { 'value': 'contact.event.suggest.value'|trans, 'attr': {'class': 'fr-select'}}) }}
                        </div>
                    </div>
                {% else %}
                    <div class="fr-input-group">
                        <div class="fr-select-group">
                            {{ form_label(contactForm.subject, '', {
                                'label_attr': {'class': 'fr-label'}
                            }) }}
                            {{ form_widget(contactForm.subject, { 'attr': {'class': 'fr-select'}}) }}
                        </div>
                        <div class="conditional-field">
                            {{ form_label(contactForm.other, '', {
                                'label_attr': {'class': 'fr-label'}
                            }) }}
                            {{ form_widget(contactForm.other, { 'attr': {'class': 'fr-input'}}) }}
                            {% if form_errors(contactForm.other) is not empty %}
                                <div class="fr-error-text form-error-li-none align-items-baseline">
                                    {{ form_errors(contactForm.other) }}
                                </div>
                            {% endif %}
                        </div>
                    </div>
                {% endif %}
                
                <div class="fr-input-group">
                    {{ form_label(contactForm.email, '', {
                        'label_attr': {'class': 'fr-label'}
                    }) }}
                    <div class="fr-input-wrap fr-fi-error-warning-line">
                        {{ form_widget(contactForm.email, { 'attr': {'class': 'fr-input', 'placeholder': 'contact.placeholder.email'|trans }}) }}
                    </div>
                    {% if form_errors(contactForm.email) is not empty %}
                        <div class="fr-error-text form-error-li-none align-items-baseline">
                            {{ form_errors(contactForm.email) }}
                        </div>
                    {% endif %}
                </div>
                
                {% if contactForm.captcha is defined %}
                    <div class="fr-input-group">
                        {{ form_label(contactForm.captcha, 'Captcha', {
                            'label_attr': {'class': 'fr-label'}
                        }) }}
                        <div class="fr-input-wrap fr-fi-error-warning-line">
                            {{ form_widget(contactForm.captcha, { 'attr': {'class': 'fr-input'}} ) }}
                        </div>
                        {% if form_errors(contactForm.captcha) is not empty %}
                            <div class="fr-error-text form-error-li-none align-items-baseline">
                                {{ form_errors(contactForm.captcha) }}
                            </div>
                        {% endif %}
                    </div>
                {% endif %}
                
                {% if contactForm.ref is defined %}
                    <div class="ref-special">
                        {{ form_widget(contactForm.ref, { 'attr': {'class': 'ref-special','tabindex':'-1'}} ) }}
                    </div>
                {% endif %}
                
                <div class="fr-input-group">
                    {{ form_label(contactForm.message, '', {
                        'label_attr': {'class': 'fr-label'}
                    }) }}
                    <div class="fr-input-wrap fr-fi-error-warning-line">
                        {{ form_widget(contactForm.message, { 'attr': {'class': 'fr-input'}}) }}
                    </div>
                    {% if form_errors(contactForm.message) is not empty %}
                        <div class="fr-error-text form-error-li-none align-items-baseline">
                            {{ form_errors(contactForm.message) }}
                        </div>
                    {% endif %}
                </div>
                
                <div class="fr-input-group">
                    <button type="submit" class="fr-btn">
                        {{ 'button.send'|trans }}
                    </button>
                    <input type="button" id="btnresetform" value="{{ 'front.reset.button'|trans }}" class="fr-btn fr-btn--secondary">               
                </div>
                
                {{ form_end(contactForm) }}
            
            {% endif %}
        
        </div>
    </div>
</div>

templates/partials/contact/_maincontact.html.twig
<main class="fr-fluid" role="main">
    {% block main %}
        {% include 'partials/contact/_bannercontact.html.twig' %}
        {% block page %}
            {% include 'partials/contact/_contact.html.twig' %}
        {% endblock %}
        {% include 'partials/common/_search-footer.html.twig' %}
    {% endblock %}
</main>